### ISSUE TITLE
Does not work with Ember 1.8.1

### ISSUE THREAD

**Issue by rianrainey** [kurko/ember-localstorage-adapter#93]
This adapter worked for me through Ember 1.7, but when I tried Ember 1.8, it breaks and I get `Uncaught TypeError: undefined is not a function` on ember.js:17100 which is this line here for me:

```
var isPathCache       = new Cache(1000, function(key) { return key.indexOf('.')      !== -1; });
```

**Comment by kurko** [comment]
I just updated to `ember-data.beta.14.1` and it works :grin:
